import {test,expect,tranNgang} from './support/fixtures.mjs';
import {TK,duLieuMau} from './support/du-lieu-mau.mjs';
test('Phân quyền: cấp Video riêng, không tự thêm quyền xuất bản, ghi lịch sử',async({page,moTrang},info)=>{
  await moTrang({nguoi:TK.quanLy,hash:'duyet'});
  await page.locator(`[data-pqsua="${TK.giaoVien}"]`).click();
  await page.locator('#pq-them').click();
  await page.locator('#pq-luu').click();
  await expect(page.locator('#toast')).toContainText('Đã lưu quyền');
  const p=await page.evaluate(m=>window.__FAKE_FB.docs.get('phanquyen/'+m),TK.giaoVien);
  expect(Object.values(p.cap).flatMap(g=>g.a)).toEqual(['VIEW']);
  expect(await page.evaluate(m=>[...window.__FAKE_FB.docs.keys()].filter(k=>k.startsWith('phanquyen/'+m+'/ls/')).length,TK.giaoVien)).toBe(1);
  expect(await tranNgang(page)).toBeLessThanOrEqual(1);
  await info.attach('phan-quyen',{body:await page.locator('#pq-goc').screenshot(),contentType:'image/png'});
});
test('Chat: hội thoại riêng từng tài khoản, phục hồi an toàn và tải Markdown',async({page,moTrang},info)=>{
  await moTrang({nguoi:TK.hocVien});
  await page.locator('#tl-chat-nut').click();
  await page.locator('#tl-nd').fill('Lịch học');
  await page.locator('#tl-go button[type=submit]').click();
  await page.locator('#tl-history-toggle').click();
  await expect(page.locator('[data-conversation]')).toHaveCount(1);
  await page.locator('#tl-new').click();
  await page.locator('#tl-history-toggle').click();
  await page.locator('[data-conversation]').click();
  await expect(page.locator('#tl-tin')).toContainText('Lịch học');
  await expect(page.locator('#tl-tin')).toContainText('Bình Phú');
  const download=page.waitForEvent('download');await page.locator('#tl-export').click();expect((await download).suggestedFilename()).toMatch(/\.md$/);
  expect(await tranNgang(page)).toBeLessThanOrEqual(1);
  await info.attach('chat',{body:await page.screenshot(),contentType:'image/png'});
  await page.evaluate(m=>window.__fakeAuth.dangNhap(m),TK.giaoVien);
  await page.reload();await page.waitForFunction(()=>window.__appOk===true);
  await page.locator('#tl-chat-nut').click();await page.locator('#tl-history-toggle').click();
  await expect(page.locator('[data-conversation]')).toHaveCount(0);
});
